# Generated by Django 4.2 on 2025-05-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='Содержимое статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Изображение статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250, verbose_name='Каталог')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Каталог',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(verbose_name='Наш город')),
                ('history', models.TextField(verbose_name='История компании')),
                ('catalog_xbik', models.FileField(upload_to='catalogs/', verbose_name='Каталог ЖБИ')),
                ('typical_contract', models.FileField(upload_to='contracts/', verbose_name='Типовой договор')),
                ('concrete_contract', models.FileField(upload_to='contracts/', verbose_name='Договор на поставку товарного бетона')),
                ('xbik_contract', models.FileField(upload_to='contracts/', verbose_name='Договор на поставку ЖБИ')),
            ],
            options={
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('map_photo', models.ImageField(blank=True, null=True, upload_to='contacts/maps/', verbose_name='Фото c карты')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваш адрес электронной почты')),
                ('phone', models.CharField(max_length=20, verbose_name='Ваш номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('object_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект')),
                ('project_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Название продукта')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='Главное изображение')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Дополнительное изображение 1')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Дополнительное изображение 2')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Дополнительное изображение 3')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nukusbeton.brand', verbose_name='Каталог')),
            ],
            options={
                'verbose_name_plural': 'Продукт',
            },
        ),
    ]
