# Generated by Django 4.2 on 2025-05-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
