# Generated by Django 4.2 on 2025-05-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0002_delete_category_remove_article_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
