# Generated by Django 4.2 on 2025-05-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('map_photo', models.ImageField(blank=True, null=True, upload_to='contacts/maps/', verbose_name='Фото c карты')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
