# Generated by Django 4.2 on 2025-05-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
