# Generated by Django 4.2 on 2025-05-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0005_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='catalog_xbik',
        ),
        migrations.RemoveField(
            model_name='company',
            name='concrete_contract',
        ),
        migrations.RemoveField(
            model_name='company',
            name='typical_contract',
        ),
        migrations.RemoveField(
            model_name='company',
            name='xbik_contract',
        ),
    ]
