# Generated by Django 4.2 on 2025-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0006_remove_company_catalog_xbik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название договора')),
                ('file', models.FileField(upload_to='docs/', verbose_name='Файл договора')),
            ],
        ),
    ]
