# Generated by Django 4.2 on 2025-05-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0008_alter_document_options_extraimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraImage',
        ),
    ]
