# Generated by Django 4.2 on 2025-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0009_delete_extraimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Вставь ссылку с YouTube или Vimeo')),
            ],
        ),
    ]
