# Generated by Django 4.2 on 2025-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0010_productionphoto_productionvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
