# Generated by Django 4.2 on 2025-05-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0011_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionvideo',
            name='url',
        ),
        migrations.AddField(
            model_name='productionvideo',
            name='video',
            field=models.FileField(default=2, upload_to='media/videos/'),
            preserve_default=False,
        ),
    ]
