# Generated by Django 4.2 on 2025-07-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nukusbeton', '0012_remove_productionvideo_url_productionvideo_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionphoto',
            options={'verbose_name_plural': 'Фото производства'},
        ),
        migrations.AlterModelOptions(
            name='productionvideo',
            options={'verbose_name_plural': 'Видео производства'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на статью'),
        ),
    ]
